version: '3.8'

services:
  linebot:
    build: .
    ports:
      - "8080:8080"
    env_file: .env

  ngrok:
    image: ngrok/ngrok:latest
    command: ["http", "linebot:8080"]
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
